name: Greeting Workflow
on:
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a greeting
        run: echo "CI PIPLELINE STARTED!!!"

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run Python Tests
        run: python3 test_calc.py
